### ISSUE TITLE
software could not be found on any servers at this time / Need help with package creation

### ISSUE THREAD

**Issue by Frxhb** [Romanitho/Winget-Install#91]
I am trying to implement this, but always the error: software could not be found on any servers at this time

Can you maybe provide a step-by-step instruction with screenshots on how to get there and how to build for example a notepad++ package? I swear, I am trying this for hours and cant get it work.

**Comment by KnifMelti** [comment]
https://github.com/Romanitho/Winget-Install/discussions/59#discussioncomment-7444310

**Comment by Frxhb** [comment]
> [#59 (comment)](https://github.com/Romanitho/Winget-Install/discussions/59#discussioncomment-7444310)

Thanks, but this is for Intune and I meant SCCM, sorry.

**Comment by Romanitho** [comment]
Same. Just use `powershell.exe` instead of the sysnative path.

**Comment by KnifMelti** [comment]
> Thanks, but this is for Intune and I meant SCCM, sorry.

I'll create a step-by-step instruction with screenshots when I'm at work again (I have in the moment 20+ WinGet-apps Available for users to self install/uninstall both in System as User context through Software Center)

**Comment by KnifMelti** [comment]
**Klogg (WinGet)** as Available application in SCCM (installs in **System** context) via `%ProgramData%\winget-install.ps1`:

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/161df5fa-4ab2-4852-91d7-8243db30955c)

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/7cfc28cc-21b5-465f-84e4-1c9d910ecf1a)

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/02fe5b97-9cd5-4506-9b15-d50d82baaf2e)

`powershell.exe -NoProfile -ExecutionPolicy Bypass -File %ProgramData%\winget-install.ps1 -AppIDs variar.klogg`
`powershell.exe -NoProfile -ExecutionPolicy Bypass -File %ProgramData%\winget-install.ps1 -AppIDs variar.klogg -Uninstall`

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/8c62e545-82da-4f3e-b494-fba0c9baeaf6)

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/cdfb8198-a171-4188-bfd3-c7b3c7b35807)

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/84f3d61d-46be-42e1-b9a6-4601ef2c4d8c)

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/b4d36bb2-a70a-4be1-b69a-5436e057aee5)

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/ffe0ffcb-931d-4b99-af07-1e383f2cbedb)

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/a8653d3a-4e22-4c6d-b342-09b4690a9801)

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/5aabf2f4-8c83-424c-ae21-dcb906125723)

![image](https://github.com/Romanitho/Winget-Install/assets/102996177/d46f1672-baf5-4c55-9f64-634eccd9e800)

**Comment by KnifMelti** [comment]
> Available application

And as the original **Uninstall** uses dialogs (requires [WAU](https://github.com/Romanitho/Winget-AutoUpdate#custom-scripts-mods-feature-for-apps) if no Uninstall **Content** is used):

**C:\ProgramData\Winget-AutoUpdate\mods:**

**variar.klogg-uninstall.ps1**

```
<# ARRAYS/VARIABLES #>
#Beginning of Process Name to Wait for to End - optional wildcard (*) after, without .exe, multiple: "proc1","proc2"
$Wait = @("Un_A")

<# FUNCTIONS #>
. $PSScriptRoot\_Mods-Functions.ps1

<# MAIN #>
if ($Wait) {
    Wait-ModsProc $Wait
}

<# EXTRAS #>
```

**Comment by Romanitho** [comment]
Smart. You deploy winget-install.ps1 with another app on the Programdata. This way, you only maintain it once... 🤩

**Comment by KnifMelti** [comment]
> Smart. You deploy winget-install.ps1 with another app on the Programdata. This way, you only maintain it once... 🤩

Thanks!
Yes, WAU rolls out on all or domain computers, winget-install.ps1 is a part of it.
When upgrading WAU (and if winget-install is newer) that too gets a new file.

**Comment by KnifMelti** [comment]
...thinking of it; could actually be a part of WAU to.. ..when a new release is created it could pull the latest winget-install.psi from that Repo...

**Comment by Frxhb** [comment]
wooow thank you verry much!

**Comment by Romanitho** [comment]
Or I was thinking about that from a while, but we can add the install feature to WAU and create a kind of 'all in one' tool for winget packages...

**Comment by KnifMelti** [comment]
> a kind of 'all in one' tool for winget packages...

[Winget-Install-GUI](https://github.com/Romanitho/Winget-Install-GUI) too...

**Comment by Romanitho** [comment]
Possibly

**Comment by Frxhb** [comment]
Hi there

Thank you very much for your detailed instruction. This worked on a "older" machine, where winget worked before.

But I have the following problem:

When I pxe boot/install a new client with SCCM/MECM, WinGet seems not to work.
When you call winget in a terminal after fresh new-install, it seems to work, but if you type in for example `winget search notepad` or` winget install notepad++.notepad++` it wont load.
When you try to force update or reset the winget source, it wont work.
Only if you open the Microsoft Store and update winget there manually, winget finally works.
But at this step its too late for my task sequence, cause I added a few winget-install packages and they could not be installed until I update winget in the Microsoft Store manually.

Might you help here? 
Thanks!

**Comment by KnifMelti** [comment]
I can't help, but I can explain.
When I get home.

**Comment by KnifMelti** [comment]
**Prerequisites** for the modern **WinGet** are:
- Visual C++ 2019 or 2022
- Microsoft.VCLibs.140.00.UWPDesktop (**Server 2019** cant install that but **WinGet** runs without problems...)

The latest [winget-install.ps1](https://github.com/Romanitho/Winget-Install/blob/main/winget-install.ps1) takes care of it and pre-installs them on a client/server.
It also updates **WinGet** to the latest version by checking the **tag_name** at: https://api.github.com/repos/microsoft/winget-cli/releases/latest

So, you can use that to test (should work for installing in **System** context):
- Download [v1.11.1 Pre-release](https://github.com/Romanitho/Winget-Install/archive/refs/tags/v1.11.1.zip)
- Download the latest [RAW winget-install.ps1](https://github.com/Romanitho/Winget-Install/blob/main/winget-install.ps1) and replace the one in the Pre-release

When a new client (**Win10** and probably even **Win11**?) is deployed the "**WinGet**" is a very old version before it got named `winget.exe`.
That's why it doesn't work until the **Store** updates to the latest **WinGet** from **User** context (updating the machine **WinGet** and creating som kind of **SymLink** under `%LocalAppData%\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe`).

The **Store** can't be initialized until an user has logged on once.

So, for using **WinGet** as a deployment installer there are some caveats:
- Your deployment network needs to be able to access the whole world (not recommended at all!)
- Anything can happen when installing/uninstalling **WinGet** apps, they'll need to be extremely well tested
- **WinGet** itself can hang/crash/burn/stall...

So, the only recommended way of using this is to keep **WinGet** apps away from deployments!

**Comment by Romanitho** [comment]
The plan is to implement winget-install as a new feature to WAU, because it uses the same functions...
It will became the WAU Tools, or something like that 😅
This way, our tools will be easier to maintain. The idea is that if someone uses winget-install, it means it does probably use WAU as well,  as it exists a lot of ways to implement winget apps in intune or MECM.
So for me it makes sense that it should become an all-in-one tool 😊

**Comment by KnifMelti** [comment]
But, then you must have a way to not install it during SCCM task sequence (security, locked down deployment network) or set the task to ignore this install fail (can't reach internet) or install the prerequisites and WinGet before WAU.
My organisation has the ability to mark those applications that cannot install during deployment.

**Comment by Romanitho** [comment]
Yes, install WAU first, which will install all prerequisites. Then install apps.
Continue the task if it fails, but report those failing apps.
You can even use mods to install a default app once if winget-install fails. Obviously, the app will not be up to date, but at least you have all the apps at the end of the TS. WAU will catch things up when available.

**Comment by KnifMelti** [comment]
> * Download [v1.11.1 Pre-release](https://github.com/Romanitho/Winget-Install/archive/refs/tags/v1.11.1.zip)
> * Download the latest [RAW winget-install.ps1](https://github.com/Romanitho/Winget-Install/blob/main/winget-install.ps1) and replace the file from the Pre-release (@Romanitho maybe a new one? )
> * Wait for the next **Stable** release before using it in a production environment

Now:
- Download [v1.11.2](https://github.com/Romanitho/Winget-Install/releases/tag/v1.11.2) 😍
